
  - name: disable nodejs
    ansible.builtin.command: dnf module disable nodejs -y


  - name: enable nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: installing mysql-server
    ansible.builtin.package:
      name: "{{item}}"
      state: present  
    loop:
    - nodejs
    - mysql  


  - name: installing PYMSQL 
    ansible.builtin.pip:
      name:
      - PyMySQL 
      - cryptography     

  - name: Add the user 
    ansible.builtin.user:
     name: expense
   
 



  


 

  - name: installing dependencies
    ansible.builtin.command: npm install 
    args:
     chdir: /app    


  - name: Copy file with owner and permissions
    ansible.builtin.template:
      src: backend.service.j2
      dest: /etc/systemd/system/backend.service

  


  - name: import mysql data
    community.mysql.mysql_db:
      name: all
      state: import
    
      login_user: root
      login_password: ExpenseApp@1
      login_host: mysql.daws83s.shop
      target: /app/schema/backend.sql


  - name: reload the daemon
    
    ansible.builtin.systemd_service:
     name: backend
     daemon_reload: true
     state: started     
        
   




      