
  - name: installing mysql-server
    ansible.builtin.package:
      name: mysql-server
      state: present


  - name: installing PYMSQL 
    ansible.builtin.pip:
      name:
      - PyMySQL 


  - name: installing mysql-server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: Get MySQL version with non-default credentials
    community.mysql.mysql_info:
     login_user: root
     login_password: ExpenseApp@1
     login_host: mysql.daws83s.shop
    register: mysql_info
    ignore_errors: true

  - name: configuring password
    ansible.builtin.command: mysql_secure_installation --set-root-pass ExpenseApp@1
    when: mysql_info.failed is true


   

 
            